### ISSUE TITLE
Dead code in solution branch?

### ISSUE THREAD

**Issue by itzsaga** [learn-co-curriculum/forms-and-basic-associations-rails-lab#13]
In the solution branch, the `SongsController` has `p song_params` in the `create` method. What is that? Why is it there?

I had a student ask me and I had no reasoning to give him.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
