### ISSUE TITLE
form_spec and model spec require two different genre setters to pass?

### ISSUE THREAD

**Issue by ThePeej** [learn-co-curriculum/forms-and-basic-associations-rails-lab#14]
In song_form_spec.rb, the test to create a song with a genre is looking for a song_genre_id field 

`select 'Alternative', from: 'song_genre_id'`

which I understand will mean that a genre_id=(id) setter will be needed in the Song model. This will also mean that the strong params will need to permit :genre_id. However, in song_spec.rb, it tests for a genre_name setter and getter method, as well.

`song.genre_name = 'Rock'`

Working through the specs, I was struggling to get all the tests passing. It was a bit confusing having to write both genre setter/getter methods into the Song model to get the tests to pass. I also noticed that the genre_id setter/getter was not included into the solution, and I was not able to pass the lab without those methods. As I was looking through the history of the solution branch, I noticed that the New form did use :genre_name at one point before being switched over to :genre_id.

**Comment by catherinism** [comment]
I agree.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the README and believe your issue to have been resolved, although, for this particular lab the tests pass without a `genre_id` getter/setter.

We apologize for the frustration you've encountered during this process but thank you for helping us ensure that it help others from facing the same issues.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
