### ISSUE TITLE
note_contents=

### ISSUE THREAD

**Issue by BarbaraPruz** [learn-co-curriculum/forms-and-basic-associations-rails-lab#15]
On the solution, I noticed 2 odd things about the note_contents= implementation.  I'm not sure if these are intentional.  

1) Say you have an existing song s with note_contents ["note 1", "note 2"].  If you call s.note_contents=["Revised Notes"], it looks like the note contents are now "note 1", "note 2" and "Revised Notes".  I think I would have expected the old notes to be replaced by the new assignment.

2) Lets say there is a song s1 with note "Recorded July 2018" and another song s2 with note "Recorded July 2018".  It looks like both these songs will be pointing to the same note id.   It seems that this could lead to problems (like if s1 is deleted including references to notes, then s2 will be missing its note?)

Was this behavior intended?  I tried to address 2nd item in my implementation but I think a little messy
  def note_contents=(arry)
    arry.delete_if(&:blank?).each { |c|
       if !Note.find_by(content: c, song_id: self.id)
         self.notes.build(content: c)
       end
     }
 end

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
