### ISSUE TITLE
Lesson did not cover this lab

### ISSUE THREAD

**Issue by JoeQuattrone** [learn-co-curriculum/forms-and-basic-associations-rails-lab#16]
Confusing lab. The previous lesson did not do a good job of explaining the data flow in this lab as well as the methods. The method below was not discussed at all in the previous lab and it's not intuitive.

```def note_contents=(notes)
    notes.each do |content|
      if content.strip != ''
        self.notes.build(content: content)
      end
    end
  end

  def note_contents
    self.notes.map(&:content)
  end

**Comment by PrincessLaurora** [comment]
I agree with you, these labs are more and more frustrating. Poorly explained, not updated and full of mistakes.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe this issue to have been resolved.
We'll also take this information into consideration in upcoming releases of this curriculum.
As always, thanks for contributing! 💙
