### ISSUE TITLE
Doesn't use custom setter and getter for genre_name after having you make it

### ISSUE THREAD

**Issue by Mera-Stackhouse** [learn-co-curriculum/forms-and-basic-associations-rails-lab#18]
Also test mentions a datalist? Should we use a datalist? The solution doesn't use a datalist I don't think. So the the test information doesn't help you to solve the problem when it mentions something you don't need to use.

**Comment by drakeltheryuujin** [comment]
Hi there,
Thank you for spotting this issue and providing feedback.
I'm having difficulty understanding the issue (I'm not seeing these issues with the tests and the expectations of the lab), so I'm going to close it for now.

If you can provide further detail about how this could be addressed, I'd be happy to take a second look!

As always, thanks for contributing! 💙
